### ISSUE TITLE
Could you share the pre-trained model by gogole drive or anything else baidu service

### ISSUE THREAD

**Issue by onoderay** [ZhihengCV/Bayesian-Crowd-Counting#10]
Hello,  first of all, I appreciate your work and sharing the code.
But, I couldn't download the pretrained model because I don't have Chinese VPN and mobile phone number which is necessary to register for baidu service (as far as I understand it)
So, it would be nicer if you would share the pretrained model by other sharing methods, such as google drive, anything else.
Thanks in advance.

**Comment by ZhihengCV** [comment]
The google drive link has been uploaded, have fun:)
