### ISSUE TITLE
cant try my original dataset

### ISSUE THREAD

**Issue by onoderay** [ZhihengCV/Bayesian-Crowd-Counting#13]
Hello, I was trying to count my original crowd images, but i cant test by your test.py script because it needs pre_process and the pre_process.py scripts needs annotation file which is obviously unavailable.
So is there any way to count with my original dataset?

**Comment by ZhihengCV** [comment]
You can modify test.py , the code is pretty easy.

**Comment by onoderay** [comment]
you dont understand english

**Comment by onoderay** [comment]
and your code have ton of bugs
