### ISSUE TITLE
How to pre-process the ShanghaiTech dataset?

### ISSUE THREAD

**Issue by tfzhang006** [ZhihengCV/Bayesian-Crowd-Counting#26]
I find that you have released the pre-processing code for QNRF, but how can I get the pre-processed data for ShanghaiTechA/B dataset?

**Comment by navsgit** [comment]
Hi could you please answer the question.
thanks

**Comment by ImMrMa** [comment]
Hello, I also encountered the corresponding problem, have you finally solved it?

**Comment by xcaizewu** [comment]
[pre_data.txt](https://github.com/ZhihengCV/Bayesian-Crowd-Counting/files/14416379/pre_data.txt)
@navsgit @ImMrMa
