### ISSUE TITLE
The meaning of the density graph?

### ISSUE THREAD

**Issue by ikaroso** [ZhihengCV/Bayesian-Crowd-Counting#27]
I am a new learner in this area, there is a naive question. With this model, i can get a density graph for my own pictures. So, what is the meaning of each point's value in the density graph? Is it the value of crowd density in that pixel?

这个问题我在谷歌了好久也没搞懂。请问一下，最后生成的人群密度热力图里，每个点的值代表什么意思呢。是代表该点人群密度的值吗，因为密度越高的地方值越大。那么，是否可以说，如果这个点的值是3，就代表网络预测这个点有三个人。麻烦各位大神回答一下，我知道这个问题应该很傻，谢谢了。

**Comment by ikaroso** [comment]
I just get it know.

**Comment by xingchenfys** [comment]
请问这个密度图最终是怎么理解的呢

**Comment by ikaroso** [comment]
@xingchenfys 矩阵里每个位置的值代表人数，图例人数总和等于矩阵的sum。应该是这样，你可以随便找个图验证一下，我也不确定。时间太久忘的差不多了。

**Comment by xingchenfys** [comment]
请问在test.py文件里得到的的概率密度图嘛？那场景的密度图是怎么得到的呢？辛苦您啦
