### ISSUE TITLE
How is the density map D^est generated?

### ISSUE THREAD

**Issue by CassieMai** [ZhihengCV/Bayesian-Crowd-Counting#3]
Hello, @ZhihengCV. In your paper, there is no much explanation about the density map D^{est}. How is the D^{est} generated? Is it the output of the regressor? What is the loss used to learn the density map? Is the loss the same as the loss L^{Bayes} for the posterior estimation? Thank you.

**Comment by ZhihengCV** [comment]
It is predicted by a fully convolutional network, which is VGG19 in our paper.

**Comment by CassieMai** [comment]
There is two loss in your model, right? One is the Bayesian loss for point supervision and the other for training the D^est. Is the loss for training D^est the pixel-wise loss?

One more question is about p(y_n|x_m). The value of y_n varies from one image to another image. That is, N is different for each image. The N of a test image is also different from that of training images. What is the value field of y_n in training?
