### ISSUE TITLE
What is the p(x_m|y_n) in the testing stage?

### ISSUE THREAD

**Issue by CassieMai** [ZhihengCV/Bayesian-Crowd-Counting#4]
Hi. There are no parameters learned for the Bayesian model. In the training stage, p(x_m|y_n) can be obtained from the ground truth density map. But in the testing stage, how we get the p(x_m|y_n)? Did I miss something?

**Comment by xingxjtu** [comment]
There is no need to get p(x_m|y_n) in the testing stage since it can be eliminated as shown in Eq.(7).

**Comment by CassieMai** [comment]
@xingxjtu Thank you.
