### ISSUE TITLE
About releasing the code

### ISSUE THREAD

**Issue by wuqiyao20160118** [ZhihengCV/Bayesian-Crowd-Counting#6]
Hello!
The idea of constructing bayesian method in crowd counting is awesome! I'd like to reproduce or improve your work, but is there any specific plan to share your code with us? (ex. when to release the code) For it has been 27 days since you issued the rough plan. I'll really appreciate it if the code is released. Thanks!

**Comment by Belye** [comment]
请问下 代码还公开吗？
