### ISSUE TITLE
code environment

### ISSUE THREAD

**Issue by chen-judge** [ZhihengCV/Bayesian-Crowd-Counting#7]
Could you publish your requirements.txt？
I wish to know your environment such as pytorch and python version, etc.
Thank you!

**Comment by ZhihengCV** [comment]
python 3.0 pytorch >1.0, I will release the complete code and readme this week

**Comment by ZhihengCV** [comment]
python 3.6 pytorch >1.0, I will release the complete code and readme this week

**Comment by chen-judge** [comment]
I have trained a model with your code successfully，the result is excellent.
Thanks!

**Comment by srinadhu** [comment]
@chen-judge  were you able to reproduce on the ShanghaiTech part A dataset as well? If Yes please let me know what are the settings you used? @ZhihengCV seems to never respond to this query at all. Thanks.
