### ISSUE TITLE
关于 regression 模块的参数

### ISSUE THREAD

**Issue by wyj1158965943** [ZhihengCV/Bayesian-Crowd-Counting#9]
您可以把 regression 模块那三个卷积层的参数文件上传到 Github 吗？

**Comment by wyj1158965943** [comment]
抱歉，我仔细读了源码，发现VGG19的参数也被优化了，所以您可以传一下整个模型的参数吗？非常感谢

**Comment by ZhihengCV** [comment]
The pretrained weight has been uploaded
